name: Debug
on:
  workflow_dispatch:
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Debug echo
        run: |
          filename="MY_FILE.TXT"
          echo "::error::Filename $filename doen't match possible files" && exit 1
