name: Workflow with error handling
on:
  workflow_dispatch:
jobs:
  Job-with-error-handling:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Produces error but continues
        id: step1
        run: |
          echo "This is Step 1"
          echo "::error::This is an error message from Step 1"
        continue-on-error: true

      - name: Step 2 - Produces error but continues
        id: step2
        run: |
          echo "This is Step 2"
          echo "::error::This is an error message from Step 2"
        continue-on-error: true

      - name: Step Show Errors - Shows the error in annotation, if any produced
        id: stepShowErrors
        run: |
          echo "This is Step Show Errors"
          if [[ "${{ steps.step1.outcome }}" == "failure" ]]; then
            echo "::error file=(path to your file),line=(line number),col=(column number)::${{ steps.step1.outputs.error }}"
          fi
          if [[ "${{ steps.step2.outcome }}" == "failure" ]]; then
            echo "::error file=(path to your file),line=(line number),col=(column number)::${{ steps.step2.outputs.error }}"
          fi
        continue-on-error: true

      - name: Step Final - Finishes the workflow
        id: stepFinal
        run: |
          echo "This is Step 3"
          echo "Workflow finished successfully!"
