name: Workflow with error handling
on:
  workflow_dispatch:
jobs:
  Job-with-error-handling:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Produces error but continues
        id: step1
        run: |
          echo "This is Step 1"
          echo "::error::This is an error message from Step 1"
        continue-on-error: true

      - name: Step 2 - Shows the error in annotation, if any produced
        id: step2
        run: |
          echo "This is Step 2"
          if [[ "${{ steps.step1.outcome }}" == "failure" ]]; then
            echo "::error file=(path to your file),line=(line number),col=(column number)::${{ steps.step1.outputs.error }}"
          fi
        continue-on-error: true

      - name: Step 3 - Finishes the workflow
        id: step3
        run: |
          echo "This is Step 3"
          echo "Workflow finished successfully!"
